version: "3.8"

services:
  backend:
    build: .
    container_name: solana-backend-fs
    env_file: backend/.env
    ports:
      - "3000:3000"
    depends_on:
      - redis

  redis:
    image: "redis:alpine"
    ports:
      - "6379:6379"
